-   id: mdspell
    name: markdown-spellcheck
    description: ''
    entry: mdspell
    language: node
    'types': [markdown]
    args: []
    require_serial: false
    additional_dependencies: ["markdown-spellcheck@0.6.2"]
    minimum_pre_commit_version: '0'
